ДЗ-2: добавлены компоненты, добавлены табы и счётчик блюд
VitaliyKrasnov/learnjs-react pull request #2
Opened 2024-07-22 10:51 UTC by VitaliyKrasnov

2024-07-23 09:24 UTC, zubkov7 commented on src/components/counter/component.jsx
> +export const Counter = ({ dishAmount, incDishAmount, decDishAmount }) => {
лучше пропсы называть абстрактно, компонент каунтера может существовать отдельно от блюда

2024-07-23 09:28 UTC, zubkov7 requested changes

2024-07-23 09:28 UTC, zubkov7 commented on src/components/layout/component.jsx
> +    const [activeRestaurant, setActiveRestaurant] = useState({ id: restaurants[0].id });
логика по работе с табами - не логика компонента layout, необходимо ее вынести в отдельный компонент и передавать через children в layout

2024-07-23 09:28 UTC, zubkov7 commented on src/components/layout/component.jsx
> +    const [activeRestaurant, setActiveRestaurant] = useState({ id: restaurants[0].id });
в данном кейсе мы устанавливаем айди, поэтому лучше переименовать, чтобы переменные отражали то, что они хранят

[activeRestaurantId, setActiveRestaurantId]

айдишник не нужно передавать полем объекта, лучше просто значением

2024-07-23 09:28 UTC, zubkov7 commented on src/constants/mock.js
> +      // {
если код не нужен, то лучше удалить. Если нужен, то убрать закомментирование

2024-07-23 11:03 UTC, VitaliyKrasnov commented on src/constants/mock.js
> +      // {
удалил

2024-07-23 11:04 UTC, VitaliyKrasnov commented on src/components/layout/component.jsx
> +    const [activeRestaurant, setActiveRestaurant] = useState({ id: restaurants[0].id });
переименовал на activeRestaurantId и setActiveRestaurantId

2024-07-23 11:05 UTC, VitaliyKrasnov commented on src/components/layout/component.jsx
> +    const [activeRestaurant, setActiveRestaurant] = useState({ id: restaurants[0].id });
вот тут немного не понял про children и layout
сделал отдельный компонент TabsSection как контейнер для Tab и использую его в layout-е

2024-07-23 11:06 UTC, VitaliyKrasnov commented on src/components/counter/component.jsx
> +export const Counter = ({ dishAmount, incDishAmount, decDishAmount }) => {
переименовал на абстрактные value, increment, decrement

2024-07-23 11:15 UTC, VitaliyKrasnov commented on src/components/counter/component.jsx
> +export const Counter = ({ dishAmount, incDishAmount, decDishAmount }) => {
Андрей, подскжи, пожалуйста, в чём может быть проблема такого поведения:
при смене активного ресторана сохраняются количества блюд в счётчиках!!!????
Т.е. вот выбираю последний ресторан, увеличиваю счётчик первого блюда, перехожу на первый ресторан - счётчик у первого блюда тоже увеличился!

2024-07-24 14:20 UTC, zubkov7 commented on src/components/counter/component.jsx
> +export const Counter = ({ dishAmount, incDishAmount, decDishAmount }) => {
при рендере активного ресторана добавьте проп key с айдишником ресторана, проблема уйдет. Мы на лекциях будем разбирать подробнее рендеринг и key еще

2024-07-24 14:23 UTC, zubkov7 commented on src/components/layout/component.jsx
> +    const [activeRestaurant, setActiveRestaurant] = useState({ id: restaurants[0].id });
задача компонента Layout - отобразить основные элементы страницы. Его должен использовать компонент App и наполнять необходимыми компонентами. Поэтому нужно логику работы с табами вынести в отдельный компонент, в App использовать Layout и через подход с children передавать необходимые компоненты, как разбирали на лекции

2024-07-25 06:13 UTC, VitaliyKrasnov commented on src/components/layout/component.jsx
> +    const [activeRestaurant, setActiveRestaurant] = useState({ id: restaurants[0].id });
спасибо за пояснения, постарался переделать как вы объяснили

2024-07-25 06:13 UTC, VitaliyKrasnov commented on src/components/counter/component.jsx
> +export const Counter = ({ dishAmount, incDishAmount, decDishAmount }) => {
понятно, спасибо!

2024-07-25 13:04 UTC, zubkov7 approved these changes

2024-07-25 14:23 UTC, merged