ДЗ-3: использование хуков useReducer для формы ревью и useEffect для прогресса при скроллинге страницы
VitaliyKrasnov/learnjs-react pull request #3
Opened 2024-08-01 12:24 UTC by VitaliyKrasnov

2024-08-01 18:29 UTC, zubkov7 requested changes

2024-08-01 18:29 UTC, zubkov7 commented on src/components/scrollProgressBar/component.jsx
> +            {useEffect(() => {
эффект необходимо вызывать в теле функции самого компонента

необходимо создать состояние с помощью хука useState для ширины сайдбара и менять его значение с помощью сетера. Значение ширины передать в проп стайл

в реакте не взаимодействуем с элементами через getElementById и тд

2024-08-01 20:45 UTC, VitaliyKrasnov commented on src/components/scrollProgressBar/component.jsx
> +            {useEffect(() => {
c getElementById погорячился, прошу понять и прастить)
исправил замечание

2024-08-02 14:10 UTC, zubkov7 approved these changes

2024-08-05 20:47 UTC, merged